# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2

project_name: packs

before:
  hooks:
    - go mod tidy

builds:
  - id: packs
    main: ./cmd/packs
    binary: packs
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}

archives:
  - id: default
    formats:
      - tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"

brews:
  - name: packs
    repository:
      owner: tunajam
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
    directory: Formula
    homepage: "https://packs.sh"
    description: "Agent skill package manager - share and install AI agent skills"
    license: "MIT"
    install: |
      bin.install "packs"
    test: |
      system "#{bin}/packs", "--version"
